# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-28 20:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mathema', '0002_auto_20160421_1326'),
    ]

    operations = [
        migrations.AddField(
            model_name='atividade',
            name='arquivo',
            field=models.FileField(blank=True, null=True, upload_to=b'atividades/arquivos/atividades'),
        ),
        migrations.AlterField(
            model_name='atividade',
            name='suportes',
            field=models.ManyToManyField(blank=True, through='mathema.AtividadeSuporte', to='mathema.Suporte'),
        ),
        migrations.AlterField(
            model_name='topico',
            name='atividades',
            field=models.ManyToManyField(blank=True, through='mathema.TopicoAtividade', to='mathema.Atividade'),
        ),
        migrations.AlterField(
            model_name='topico',
            name='suportes',
            field=models.ManyToManyField(blank=True, through='mathema.TopicoSuporte', to='mathema.Suporte'),
        ),
    ]
