# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-28 20:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programacao', '0002_avaliador'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='alunos',
            field=models.ManyToManyField(blank=True, through='programacao.AlunoCurso', to='programacao.Aluno'),
        ),
    ]
